package pojo_Vin_Nickname;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class Nickname_Valid_VinID_Data_Ouput {

	 public Object assetId;
	    public Object productAttribute02;
	    public Object serialNumber;
	    public Object statusCd;
	    public Object sensitiveFlag;
	    public Object iuPrmFlag;
	    public Object amcBalance;
	    public Object maxFsc;
	    public Object lastFscNumber;
	    public Object customerRating;
	    public Object digitalCustomer;
	    public Object hsrpStage;
	    public Object joyrideBalance;
	    public Object pendingAdviceCount;
	    public Object hmglMemberType;
	    public Object hmglCardPoints;
	    public Object starCustomer;
	    public Object customerType;
	    public Object financeFlag;
	    public Object brand;
	    public Object tcuIdFlag;
	    public Object relation;
	    public Object xconSeqNum;
	    public Object firstName;
	    public Object lastName;
	    public Object hmglCardNumber;
	    public Object hmglCardCat;
	    public Object simStatus;
	    public Object amcExpiryDate;
	    public Object insuranceExpiryDate;
	    public Object warrantyStartDate;
	    public Object hmglExpiryDate;
	    public Object hmglIssueDate;
	    public Object joyrideExpiryDate;
	    public Object activationDateTime;
	    public Object activationEndDateTime;
	    public Object coverStartDateTime;
	    public Object coverEndDateTime;
	    public Object sourceUpdatedDateTime;
	    public Object fifthFscDate;
	    public Object hsrpAttribute01;
	    public String vinId;
	    public String customerIdentifier;
	    public Object firstSaleDate;
	    public Object warrantyEndDate;
	    public Object color;
	    public Object model;
	    public Object cc;
	    public Object licenceNumber;
	    public Object nextServiceDueDate;
	    public Object lastServiceDate;
	    public Object partNumber;
	    public Object category;
	    public String vehicleNickName;
	    public Object isPrimaryVehicle;
	    public Object isWarrantyActive;
	    public Object mobileNo;
	    public String message;
	    public Object rcDocUrl;
	    public Object pucDocUrl;
	    public Object vehicleInsuranceDocUrl;
	    public Object programStatus;
	    public Object policyNum;
	    public Object vendorName;
	    public Object tcuId;
	    public Object configuratorTitle;
	    public Object configuratorUrl;
	    public Object isChatbot;
	    public Object chatbotUrl;
	    public Object isCommunity;
	    public Object isDashboardTheme;
	    public Object iconUrl;
	    public Object bgImageUrl;
	    public Object mainImageUrl;
	    public Object halfImageUrl;
	    public Object isPremium;
	    public Object vehicleSubscriptions;
	    public Object scratchCardStatus;
	    public Object rewardCardImageUrl;
	    public Object salesFeedback;
	    public Object displayModel;
	    public Object dealerDisplayName;
	    public Object othersDocUrl;
	    public Object rcFrontImageUrl;
	    public Object rcBackImageUrl;
	    public Object dlFrontImageUrl;
	    public Object dlBackImageUrl;
	}