package pojo_Class_GetVehicle_List;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@AllArgsConstructor
@Data
public class VehicleDetail {
	public String assetId;
    public String productAttribute02;
    public String serialNumber;
    public String statusCd;
    public String sensitiveFlag;
    public String iuPrmFlag;
    public Object amcBalance;
    public Object maxFsc;
    public String lastFscNumber;
    public Object customerRating;
    public Object digitalCustomer;
    public String hsrpStage;
    public Object joyrideBalance;
    public String pendingAdviceCount;
    public Object hmglMemberType;
    public Object hmglCardPoints;
    public Object starCustomer;
    public String customerType;
    public String financeFlag;
    public String brand;
    public Object tcuIdFlag;
    public String relation;
    public String xconSeqNum;
    public String firstName;
    public String lastName;
    public Object hmglCardNumber;
    public Object hmglCardCat;
    public Object simStatus;
    public Object amcExpiryDate;
    public Object insuranceExpiryDate;
    public Object warrantyStartDate;
    public Object hmglExpiryDate;
    public Object hmglIssueDate;
    public Object joyrideExpiryDate;
    public Object activationDateTime;
    public Object activationEndDateTime;
    public Object coverStartDateTime;
    public Object coverEndDateTime;
    public Object sourceUpdatedDateTime;
    public Object fifthFscDate;
    public String hsrpAttribute01;
    public String vinId;
    public String customerIdentifier;
    public String serviceUpdate;
    public String preCheckFlag;
    public String attrib42;
    public String firstSaleDate;
    public String description;
    public String createdDateTime;
    public String warrantyEndDate;
    public String color;
    public String invoiceNumber;
    public String model;
    public String lastJCType;
    public String warrantyKMS;
    public String primaryDealerName;
    public String engineNo;
    public String cc;
    public String lastKMRun;
    public String licenceNumber;
    public String nextServiceDueDate;
    public String lastServiceDate;
    public String updatedDateTime;
    public String jobId;
    public String primaryDealer;
    public String partNumber;
    public String category;
    public String pnrConId;
    public String vehicleNickName;
    public String isPrimaryVehicle;
    public String isWarrantyActive;
    public String mobileNo;
    public Object rcDocUrl;
    public Object pucDocUrl;
    public Object vehicleInsuranceDocUrl;
    public Object programStatus;
    public Object policyNum;
    public Object vendorName;
    public Object tcuId;
    public String configuratorTitle;
    public String configuratorUrl;
    public String isChatbot;
    public Object chatbotUrl;
    public String isCommunity;
    public String isDashboardTheme;
    public String iconUrl;
    public Object bgImageUrl;
    public String mainImageUrl;
    public String halfImageUrl;
    public String isPremium;
    public Object vehicleSubscriptions;
    public String scratchCardStatus;
    public Object rewardCardImageUrl;
    public String salesFeedback;
    public String displayModel;
    public Object dealerDisplayName;
    public Object othersDocUrl;
    public Object rcFrontImageUrl;
    public Object rcBackImageUrl;
    public Object dlFrontImageUrl;
    public Object dlBackImageUrl;
}